### seeds for words in the database

### nouns - animals
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('der', 'Hund', 'Hunde', 'dog', 'dogs', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('die', 'Katze', 'Katzen', 'cat', 'cats', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('der', 'Vogel', ' Vögel', 'bird', 'birds', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('die', 'Kuh', 'Kühe', 'cow', 'cows', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('das', 'Pferd', 'Pferde', 'horse', 'horses', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('der', 'Fisch', 'Fische', 'fish', 'fish', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('das', 'Hähnchen', 'Hähnchen', 'chicken', chickens, false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('die', 'Ente', 'Enten', 'duck', 'ducks', false, true, false, false, false, true, false, false, true, false, true, false, false, "2020-04-21 16:07:24", "2020-04-21 16:07:24");

### nouns - people
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('die', 'Frau', 'Frauen', 'woman', 'women', true, false, false, false, false, true, true, true, true, true, true, true, true, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('der', 'Mann', 'Männer', 'man', 'men', true, false, false, false, false, true, true, true, true, true, true, true, true, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('der', 'Junge', 'Jungen', 'boy', 'boys', true, false, false, false, false, true, true, true, true, true, true, true, true, "2020-04-21 16:07:24", "2020-04-21 16:07:24");
INSERT INTO nouns (gender, singular, plural, english, englishplural, person, animal, thing, place, abstract, athome, atwork, dining, hotel, travel, people, events, shopping, createdAt, updatedAt) VALUES ('das', 'Mädchen', 'Mädchen', 'girl', 'girls', true, false, false, false, false, true, true, true, true, true, true, true, true, "2020-04-21 16:07:24", "2020-04-21 16:07:24");

