"use strict";

//this code is generated by sequelize-cli by running sequelize init 
// and is placed in a file called index.js

var fs = require("fs");
var path = require("path");
var Sequelize = require("sequelize");
var basename = path.basename(module.filename);
var env = process.env.NODE_ENV || "development";
var config = require(__dirname + "/../config/config.js")[env];
var db = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

// this part looks through the models folder for ".js" files
fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== basename) && (file.slice(-3) === ".js");
  })
  .forEach(function(file) {
    var model = sequelize["import"](path.join(__dirname, file)); //imports all those .js files
    db[model.name] = model; //keys each model file into the exports Object
  });

//Associating Each Model
Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

//Both an instance of your sequelize database (sequelize) and an instance of the Sequelize library are exported.
db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
